### ISSUE TITLE
How to read postgres hstore column?

### ISSUE THREAD

**Issue by thomasnal** [imdrasil/jennifer.cr#25] opened 2017-08-29 22:08 UTC
As a user, I would like Jennifer to deserialize content of HStore column from Postgres database.

```crystal
Column verification_score is expected to be a (String | Nil) but got Slice(UInt8). (Jennifer::DataTypeMismatch)
```
```
           Column           |            Type             |                     Modifiers
----------------------------+-----------------------------+---------------------------------------------------- 
 verification_score         | hstore                      |
```
The idea behind using crystal `String` was that I can then parse the value into Hash.  Is there a way that Jennifer can automate it?  How would I do it by myself `Slice(UInt8)` does not sound right for the value such as,
```
                                                                                                                      verification_score
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
"email"=>"5", "total"=>"35", "quotes"=>"5", "selfies"=>"0", "twitter"=>"5", "facebook"=>"5", "linkedin"=>"5", "instagram"=>"0", "strengths"=>"{\"facebook\"=>1, \"instagram\"=>0, \"linkedin\"=>1, \"twitter\"=>1}", "audio_tracks"=>"5", "phone_number"=>"5"
```

**Comment by z64** [comment] 2017-08-29 22:42
I believe the issue is that `crystal-pg` does not support `hstore`.

https://github.com/will/crystal-pg#supported-datatypes

**Comment by imdrasil** [comment] 2017-08-29 23:25
Yep - officially it is not supported for now. But I already have several things which are not supported :sunglasses: . Will try to find documentation how it stores `hstore` and maybe will add some workaround to mapping it to string. But I don't promise ).

**Comment by thomasnal** [comment] 2017-08-29 23:50
:) Thanks.  I commented these fields out.  I don't use them as they have been converted to table and columns.  I am good here.

crystal-pg is preparing hstore read though https://github.com/will/crystal-pg/pull/89 

I'm good to close this issue.

**Comment by imdrasil** [comment] 2017-08-30 08:33
So for now I close this issue. When Hstore will be added to official postgres driver - will update allowed data types.

**Closed** 2017-08-30 08:36 UTC
