### ISSUE TITLE
Migrations are not being run when running specs

### ISSUE THREAD

**Issue by wJoenn** [imdrasil/jennifer.cr#450] opened 2024-03-04 21:31 UTC
I've added `Jennifer::Migration::Runner.migrate` in my `spec/spec_helper.cr` file which is required by every test files and yet pending migrations are migrated when I run my specs.

I tried looking at the source code and basically `Jennifer::Migration::Runner.pending_migration?` returns false because `Base.versions` is empty so `(Base.versions - Version.list).sort!` is empty too

This test fails
```crystal
require "../spec_helper"

describe User do
  email = "user@example.com"
  password = "password"

  describe "validations" do
    it "creates a new User with proper params" do
      user = User.new({ email: email })
      user.password = password
      user.password_confirmation = password
      user.save

      p user.errors.full_messages
      user.valid?.should be_true
    end
  end
end

# => relation "users" does not exist.
```

until I migrate manually with `KEMAL_ENV=test sam db:migrate`

**Comment by imdrasil** [comment] 2024-03-18 20:54
very likely the issue is that you don't require migration classes. It looks like it worth having extra check in runtime for this as it may not be obvious

**Comment by wJoenn** [comment] 2024-03-18 21:08
Should I do this in my `spec_helper.cr` file then ?
```crystal
require "../db/migrations/*"
Jennifer::Migration::Runner.migrate
```

**Comment by imdrasil** [comment] 2024-03-24 20:09
I merged a sanity check whether migrations were loaded and updated docs a little bit. If it covers your case feel free to close this issue )

**Closed** 2024-03-28 22:28 UTC
