### ISSUE TITLE
Duplicate query execution when included associations have no records

### ISSUE THREAD

**Issue by thomasnal** [imdrasil/jennifer.cr#24] opened 2017-08-29 21:40 UTC
As a user, if I preload association using `includes` I want Jennifer to determine empty association and use the result when the association is accessed.

Currently, when there is an empty association that is included using `includes` then Jennifer executes the query again when the association is accessed.

The following code,
```crystal
def jumios
  users = User.all
    .includes(:jumio)
    .where{_id.in [6909, 5143]}
    .to_a

  users.each do |user|
    puts "User #{user.id}: #{user.jumio.nil?}"
  end
end

class User < Jennifer::Model::Base
  ...
  has_one :jumio, Jumio
end
```
produces the following output, provided the user 6909 has no Jumio records and user 5143 has at least one Jumio record,
```crystal
2017-08-29 21:39:42 +0000:
SELECT users.*, jumios.*
FROM users
LEFT JOIN jumios ON jumios.user_id = users.id
WHERE users.id IN($1, $2)
 | [6909, 5143]
User 5143: false
2017-08-29 21:39:42 +0000:
SELECT jumios.*
FROM jumios
WHERE jumios.user_id = $1
LIMIT 1
 | [6909]
User 6909: true
```
Observe how user 6909 is queried again while 5143 is not.

The duplicate queries seriously bloat the processing time on even a simple logic.  For 10 users the time increases by 50s and 100s milliseconds.

**Comment by imdrasil** [comment] 2017-09-11 18:30
Fix for this one is in the `0.3.4` release

**Comment by thomasnal** [comment] 2017-09-15 22:24
I bring some bad news from the battlefield ;)
```crystal
2017-09-15 22:17:58 +0000:
9103 µs SELECT users.*, jumios.*
FROM users
LEFT JOIN jumios ON jumios.user_id = users.id
WHERE users.id IN($1, $2)
 | [6909, 5143]
User 5143: false
2017-09-15 22:17:58 +0000:
2256 µs SELECT jumios.*
FROM jumios
WHERE jumios.user_id = $1
LIMIT 1
 | [6909]
User 6909: true
200  | GET  "/jumios/3"  | 12.53ms
Params: id=3
```
No change to the reported behaviour.  Branch `v0.3.4` fetched today.

**Comment by thomasnal** [comment] 2017-09-23 12:06
@imdrasil What is your idea about it?  Are you going to re-open it?  Is it reproducible from my comment?  Would you need anymore data?  This is quite an appealing feature to achieve performance.

**Comment by imdrasil** [comment] 2017-10-13 21:58
@thomasnal sorry for such long response - just missed notifications about this one. In such case fill free to ping me in the email.

Will finish current bunch of improvements and will take a look

**Comment by imdrasil** [comment] 2017-10-14 00:50
found root cause - will marge it to master tomorrow

**Comment by imdrasil** [comment] 2017-10-15 01:25
@thomasnal please check out master branch - now it should be fixed (both for `#includes` and `#eager_load`)

**Comment by imdrasil** [comment] 2017-11-01 07:58
@thomasnal Did u had a chance to test it?

**Comment by thomasnal** [comment] 2017-11-14 11:56
I have holidays this week and will be able to respond to you.  I have just performed the same test on master branch jennifer.

```sh
$ shards build amber
...
Installing jennifer (master)
...
```

I am using this code,
```crystal
  def jumios
    users = User.all
      .includes(:jumio)
      .where{_id.in [6909, 5143, 5145]}
      .to_a

    users.each do |user|
      puts "User #{user.id} has no jumios: #{user.jumio.nil?}"
    end
  end

class User < Jennifer::Model::Base
  has_one :jumio, Jumio
end
```

I am expecting database will be queried on line 2.  The output below shows that query is executed on line 2 and 8.
```crystal
2017-11-14 11:24:33 +0000:
1316 µs SELECT users.*, jumios.*
FROM users
LEFT JOIN jumios ON jumios.user_id = users.id
WHERE users.id IN($1, $2, $3)
 | [6909, 5143, 5145]
User 5143 has no jumios: false
User 5145 has no jumios: false
2017-11-14 11:24:33 +0000:
1758 µs SELECT jumios.*
FROM jumios
WHERE jumios.user_id = $1
LIMIT 1
 | [6909]
User 6909 has no jumios: true
200  | GET  "/jumios/1"  | 3.89ms
Params: id=1
```


The same code in Ruby on Rails project I intend to migrate works as expected/requested,
```ruby
Started GET "/api/jumios/1" for 172.18.0.1 at 2017-11-14 11:34:54 +0000
Processing by MatchesController#jumios as JSON
  User Load (0.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" IN (6909, 5143, 5145)
  Jumio Load (1.0ms)  SELECT "jumios".* FROM "jumios" WHERE "jumios"."user_id" IN (6909, 5145, 5143)
User 6909 has no jumios: true
User 5145 has no jumios: false
User 5143 has no jumios: false
Completed 200 OK in 399ms (Views: 187.3ms | ActiveRecord: 13.1ms)
```
and the code is,
```ruby
  def jumios
    users = User
      .includes(:jumio)
      .where(id: [6909, 5143, 5145])

    users.each do |user|
      Rails.logger.info "User #{user.id} has no jumios: #{user.jumio.nil?}"
    end

    render json: {}, status: :ok
  end

```
Query is executed on line 2 only.

**Comment by imdrasil** [comment] 2017-11-14 14:59
@thomasnal try to remove all installed shards and reinstall them from scratch. In master `#includes` uses [preloading](https://github.com/imdrasil/jennifer.cr/blob/master/src/jennifer/query_builder/i_model_query.cr#L65) so can't generate JOIN part.

**Comment by imdrasil** [comment] 2018-04-08 12:08
It seems everything works well on master. Feel free to reopen this one if something still goes wrong

**Closed by imdrasil** 2018-04-08 12:08 UTC
Labels: Done, bug
